defaults: &defaults
    test: vishal
    access_blocking_duration: 2
    access_limit:
        authenticated: 50
        unauthenticated: 10

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
